
// OHLC
export const GET_OHLC = "GET_OHLC";
export const GET_OHLC_FAIL = "GET_OHLC_FAIL";
export const GET_OHLC_DAYS_LIST = "GET_OHLC_DAYS_LIST";
export const GET_OHLC_DAYS_LIST_FAIL = "GET_OHLC_DAYS_LIST_FAIL";

// buySell
export const GET_BUY_SELL = "GET_BUY_SELL";
export const GET_BUY_SELL_FAIL = "GET_BUY_SELL_FAIL";

// Bot
export const GET_PREDICTIONS = "GET_PREDICTIONS";
export const GET_PREDICTIONS_FAIL = "GET_PREDICTIONS_FAIL";
export const GET_BOT_BUY_SELL = "GET_BOT_BUY_SELL";
export const GET_BOT_BUY_SELL_FAIL = "GET_BOT_BUY_SELL_FAIL";

